import type { ThemeConfig } from '@/types'

export const themeRegistry: Record<string, ThemeConfig> = {
  folio: {
    id: 'folio',
    name: 'Folio',
    tier: 'free',
    description: 'Warm, editorial. Classic agency feel.',
    hasAlternatingSections: false,
    hasWatermark: false,
    cssVars: {
      '--t-bg-primary': '#FAF8F3',
      '--t-bg-secondary': '#F0EDE6',
      '--t-bg-surface': '#FFFFFF',
      '--t-accent': '#D4C9BB',
      '--t-accent-text': '#6B5E52',
      '--t-text-primary': '#2C2420',
      '--t-text-secondary': '#6B5E52',
      '--t-text-inverse': '#FAF8F3',
      '--t-border': '#D4C9BB',
      '--t-rule': '#C8BDB4',
      '--t-cover-bg': '#FAF8F3',
      '--t-cover-text': '#2C2420',
      '--t-cover-accent': '#D4C9BB',
      '--t-price-bg': '#F0EDE6',
      '--t-price-text': '#2C2420',
    },
  },
  dusk: {
    id: 'dusk',
    name: 'Dusk',
    tier: 'pro',
    description: 'Dark & premium. For high-ticket work.',
    hasAlternatingSections: false,
    hasWatermark: false,
    cssVars: {
      '--t-bg-primary': '#111014',
      '--t-bg-secondary': '#1A1820',
      '--t-bg-surface': '#1E1C24',
      '--t-accent': '#D4952A',
      '--t-accent-text': '#D4952A',
      '--t-text-primary': '#F5F0E8',
      '--t-text-secondary': '#A09080',
      '--t-text-inverse': '#111014',
      '--t-border': '#2A2830',
      '--t-rule': '#2A2830',
      '--t-cover-bg': '#111014',
      '--t-cover-text': '#F5F0E8',
      '--t-cover-accent': '#D4952A',
      '--t-price-bg': '#1A1820',
      '--t-price-text': '#F5F0E8',
    },
  },
  signal: {
    id: 'signal',
    name: 'Signal',
    tier: 'pro',
    description: 'Clean iOS-inspired. Modern and precise.',
    hasAlternatingSections: false,
    hasWatermark: false,
    cssVars: {
      '--t-bg-primary': '#FFFFFF',
      '--t-bg-secondary': '#F2F2F7',
      '--t-bg-surface': '#FFFFFF',
      '--t-accent': '#007AFF',
      '--t-accent-text': '#007AFF',
      '--t-text-primary': '#000000',
      '--t-text-secondary': '#6E6E73',
      '--t-text-inverse': '#FFFFFF',
      '--t-border': '#E5E5EA',
      '--t-rule': '#C7C7CC',
      '--t-cover-bg': '#007AFF',
      '--t-cover-text': '#FFFFFF',
      '--t-cover-accent': '#FFFFFF',
      '--t-price-bg': '#F2F2F7',
      '--t-price-text': '#000000',
    },
  },
  verso: {
    id: 'verso',
    name: 'Verso',
    tier: 'pro',
    description: 'Editorial. Black-and-white impact.',
    hasAlternatingSections: true,
    hasWatermark: false,
    cssVars: {
      '--t-bg-primary': '#FFFFFF',
      '--t-bg-secondary': '#111111',
      '--t-bg-surface': '#FFFFFF',
      '--t-accent': '#111111',
      '--t-accent-text': '#111111',
      '--t-text-primary': '#111111',
      '--t-text-secondary': '#555555',
      '--t-text-inverse': '#FFFFFF',
      '--t-border': '#E0E0E0',
      '--t-rule': '#111111',
      '--t-cover-bg': '#111111',
      '--t-cover-text': '#FFFFFF',
      '--t-cover-accent': '#FFFFFF',
      '--t-price-bg': '#111111',
      '--t-price-text': '#FFFFFF',
    },
  },
  cipher: {
    id: 'cipher',
    name: 'Cipher',
    tier: 'pro',
    description: 'Tech-forward. Stripe-inspired precision.',
    hasAlternatingSections: false,
    hasWatermark: true,
    cssVars: {
      '--t-bg-primary': '#FAFAFA',
      '--t-bg-secondary': '#F4F4F8',
      '--t-bg-surface': '#FFFFFF',
      '--t-accent': '#635BFF',
      '--t-accent-text': '#635BFF',
      '--t-text-primary': '#0A0A0F',
      '--t-text-secondary': '#6B7280',
      '--t-text-inverse': '#FAFAFA',
      '--t-border': '#E8E8F0',
      '--t-rule': '#635BFF',
      '--t-cover-bg': '#0A0A0F',
      '--t-cover-text': '#FFFFFF',
      '--t-cover-accent': '#635BFF',
      '--t-price-bg': '#F4F4F8',
      '--t-price-text': '#0A0A0F',
    },
  },
}

export const themeList = Object.values(themeRegistry)
